version: "3"
services:
  nexus:
    image: sonatype/nexus3
    restart: always
    container_name: nexus
    hostname: nexus
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
      - "8085:8085"
volumes:
  nexus-data: