version: '3.7'
services:
  mongodb:
    container_name: mogodb
    hostname: mongodb
    image: mongo:jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodbpass
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: