version: '3.6'
services:
  freeipa:
    hostname: ipa2.YUOR_DOMAIN
    image: freeipa/freeipa-server:rocky-9-4.10.2
    network_mode: "bridge"
    read_only: true
    container_name: freeipa-client-1
    restart: unless-stopped
    user: root
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    command: ipa-replica-install --no-ntp --server=ipa1.YUOR_DOMAIN --domain=YUOR_DOMAIN --skip-conncheck --setup-ca --principal admin --admin-password Aa123456 --force-join --unattended
 
    extra_hosts:
      - "ipa1:ip address"
      - "ipa1.damavand.cloud:ip address"
 
    ports:
      - "389:389"
      - "636:636"
      - "88:88/udp"
      - "88:88/tcp"
      - "464:464/udp"
      - "464:464/tcp"
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/ipa-data:/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup
 
    environment:
      - DEBUG_NO_EXIT=1